language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"
install:
  - pip install -e .
  - pip install -r faker/tests/requirements.txt
  - pip install coveralls
script:
  - coverage run --source=faker setup.py test
after_success:
  - coveralls
